/* TEE Enclave — trusted code for AutoBahn fair-ordering timestamps.
 *
 * Security guarantees (upheld in hardware SGX, simulated here):
 *   1. Monotonic clock: timestamps never go backward (enforced by g_tee_clock).
 *   2. No double-attestation: each transaction hash is in g_seen_set at most once.
 *   3. Signing key never leaves the enclave (hardware-sealed in non-SIM mode).
 *
 * Signing scheme (SIM mode — benchmarking):
 *   In SIM mode, ECDSA-P256 takes ~5ms per operation, making 100 tx/block = 500ms
 *   per block — far exceeding the Δ=50ms fairness window.  We use HMAC-SHA256
 *   with a randomly-generated enclave-internal key instead.  HMAC is ~0.01ms,
 *   keeping signing within Δ even in SIM mode.  In hardware SGX, ECDSA-P256 with
 *   Intel's IPP library is ~50-150μs per op, so hardware builds could use ECDSA.
 *
 *   signed_data = hash[32] || timestamp_le[8]
 *   mac[32]     = HMAC-SHA256(g_hmac_key, signed_data)
 *   sig_out[64] = mac[32] || zeros[32]
 */

#include "tee_enclave_t.h"  /* generated by sgx_edger8r */

#include <sgx_trts.h>
#include <sgx_tcrypto.h>
#include <string.h>
#include <stdint.h>
#include <unordered_set>
#include <string>

/* ---- Enclave state (protected by enclave memory encryption in HW mode) ---- */
static bool                           g_initialized = false;
/* HMAC key: 32 random bytes generated once at enclave init. */
static uint8_t                        g_hmac_key[32];
/* Public key bytes exposed to host for identification (random, not ECDSA). */
static uint8_t                        g_pubkey_bytes[64];
static int64_t                        g_tee_clock   = 0;
static int64_t                        g_seq_counter = 0;  /* BOF sequence counter */
static std::unordered_set<std::string>* g_seen_set  = nullptr;
static std::unordered_set<std::string>* g_bof_seen  = nullptr; /* separate seen-set for BOF */

/* Convert a binary buffer to a lowercase hex string (for seen-set keys). */
static std::string to_hex(const uint8_t* data, size_t len) {
    static const char h[] = "0123456789abcdef";
    std::string s(len * 2, '0');
    for (size_t i = 0; i < len; i++) {
        s[i * 2]     = h[data[i] >> 4];
        s[i * 2 + 1] = h[data[i] & 0xf];
    }
    return s;
}

/* ---- ECALLs ---- */

sgx_status_t ecall_init_tee(uint8_t* pubkey_out) {
    if (g_initialized) {
        memcpy(pubkey_out, g_pubkey_bytes, 64);
        return SGX_SUCCESS;
    }

    /* Generate a random HMAC key and a random "public key" identifier. */
    sgx_status_t ret = sgx_read_rand(g_hmac_key, sizeof(g_hmac_key));
    if (ret != SGX_SUCCESS) return ret;
    ret = sgx_read_rand(g_pubkey_bytes, sizeof(g_pubkey_bytes));
    if (ret != SGX_SUCCESS) return ret;

    g_seen_set   = new std::unordered_set<std::string>();
    g_bof_seen   = new std::unordered_set<std::string>();
    g_initialized = true;

    memcpy(pubkey_out, g_pubkey_bytes, 64);
    return SGX_SUCCESS;
}

sgx_status_t ecall_timestamp_txn(
        const uint8_t* hash,
        int64_t*       timestamp_out,
        uint8_t*       sig_out)
{
    if (!g_initialized) return SGX_ERROR_INVALID_STATE;

    /* Deduplication: the TEE attests each transaction at most once. */
    std::string key = to_hex(hash, 32);
    if (g_seen_set->count(key)) {
        return SGX_ERROR_INVALID_PARAMETER;  /* already attested */
    }

    /* Get time from host via OCALL; enforce monotonicity inside the enclave. */
    int64_t t = 0;
    ocall_get_time(&t);
    if (t <= g_tee_clock) t = g_tee_clock + 1;
    g_tee_clock    = t;
    *timestamp_out = t;

    g_seen_set->insert(key);

    /* Build signed message: hash[32] || timestamp_le[8] */
    uint8_t msg[40];
    memcpy(msg, hash, 32);
    int64_t ts = t;
    for (int i = 0; i < 8; i++) msg[32 + i] = (uint8_t)(ts >> (i * 8));

    /* HMAC-SHA256 over msg using the enclave's random key.
     * Output: first 32 bytes of sig_out = MAC; remaining 32 bytes = 0. */
    memset(sig_out, 0, 64);
    sgx_status_t ret = sgx_hmac_sha256_msg(msg, sizeof(msg),
            g_hmac_key, sizeof(g_hmac_key),
            sig_out, 32);
    return ret;
}

/* Algorithm 4 (BOF): assign a monotonically increasing sequence number.
 * Uses a separate seen-set so OL and BOF attestations are independent.
 * The signed message has the same layout as ecall_timestamp_txn:
 *   msg = hash[32] || seq_le[8]
 * so the host can verify with the same TeeHost::Verify() logic. */
sgx_status_t ecall_assign_sequence_number(
        const uint8_t* hash,
        int64_t*       seq_out,
        uint8_t*       sig_out)
{
    if (!g_initialized) return SGX_ERROR_INVALID_STATE;

    std::string key = to_hex(hash, 32);
    if (g_bof_seen->count(key)) {
        return SGX_ERROR_INVALID_PARAMETER;  /* already attested for BOF */
    }

    int64_t seq = g_seq_counter++;
    *seq_out = seq;
    g_bof_seen->insert(key);

    uint8_t msg[40];
    memcpy(msg, hash, 32);
    for (int i = 0; i < 8; i++) msg[32 + i] = (uint8_t)(seq >> (i * 8));

    memset(sig_out, 0, 64);
    sgx_status_t ret = sgx_hmac_sha256_msg(msg, sizeof(msg),
            g_hmac_key, sizeof(g_hmac_key),
            sig_out, 32);
    return ret;
}

/* Sign arbitrary bytes (used for TEE-attested last-seen vector L⃗).
 * Uses HMAC-SHA256 for fast SIM-mode operation. */
sgx_status_t ecall_sign_bytes(
        const uint8_t* data,
        uint32_t       data_len,
        uint8_t*       sig_out)
{
    if (!g_initialized) return SGX_ERROR_INVALID_STATE;
    if (data_len == 0 || data_len > 1024) return SGX_ERROR_INVALID_PARAMETER;

    memset(sig_out, 0, 64);
    sgx_status_t ret = sgx_hmac_sha256_msg(data, (int)data_len,
            g_hmac_key, sizeof(g_hmac_key),
            sig_out, 32);
    return ret;
}

/* Verify an HMAC-SHA256 L⃗ signature inside the enclave.
 * expected_mac: first 32 bytes of the sig_out produced by ecall_sign_bytes.
 * Returns SGX_SUCCESS on match, SGX_ERROR_INVALID_PARAMETER on mismatch. */
sgx_status_t ecall_verify_bytes(
        const uint8_t* data,
        uint32_t       data_len,
        const uint8_t* expected_mac)
{
    if (!g_initialized) return SGX_ERROR_INVALID_STATE;
    if (data_len == 0 || data_len > 1024) return SGX_ERROR_INVALID_PARAMETER;

    uint8_t computed[32];
    sgx_status_t ret = sgx_hmac_sha256_msg(data, (int)data_len,
            g_hmac_key, sizeof(g_hmac_key),
            computed, sizeof(computed));
    if (ret != SGX_SUCCESS) return ret;

    uint8_t diff = 0;
    for (int i = 0; i < 32; i++) diff |= computed[i] ^ expected_mac[i];
    return (diff == 0) ? SGX_SUCCESS : SGX_ERROR_INVALID_PARAMETER;
}
