/* TEE Enclave — trusted code for AutoBahn fair-ordering timestamps.
 *
 * Security guarantees (upheld in hardware SGX, simulated here):
 *   1. Monotonic clock: timestamps never go backward (enforced by g_tee_clock).
 *   2. No double-attestation: each transaction hash is in g_seen_set at most once.
 *   3. Signing key never leaves the enclave (hardware-sealed in non-SIM mode).
 *
 * Signing scheme:
 *   signed_data = hash[32] || timestamp_le[8]   (little-endian timestamp)
 *   digest      = SHA-256(signed_data)
 *   signature   = ECDSA-P256(digest, g_priv_key)  → r[32] || s[32] (LE)
 */

#include "tee_enclave_t.h"  /* generated by sgx_edger8r */

#include <sgx_trts.h>
#include <sgx_tcrypto.h>
#include <string.h>
#include <stdint.h>
#include <unordered_set>
#include <string>

/* ---- Enclave state (protected by enclave memory encryption in HW mode) ---- */
static bool                           g_initialized = false;
static sgx_ecc_state_handle_t         g_ecc_handle  = nullptr;
static sgx_ec256_private_t            g_priv_key;
static sgx_ec256_public_t             g_pub_key;
static int64_t                        g_tee_clock   = 0;
static int64_t                        g_seq_counter = 0;  /* BOF sequence counter */
static std::unordered_set<std::string>* g_seen_set  = nullptr;
static std::unordered_set<std::string>* g_bof_seen  = nullptr; /* separate seen-set for BOF */

/* Convert a binary buffer to a lowercase hex string (for seen-set keys). */
static std::string to_hex(const uint8_t* data, size_t len) {
    static const char h[] = "0123456789abcdef";
    std::string s(len * 2, '0');
    for (size_t i = 0; i < len; i++) {
        s[i * 2]     = h[data[i] >> 4];
        s[i * 2 + 1] = h[data[i] & 0xf];
    }
    return s;
}

/* ---- ECALLs ---- */

sgx_status_t ecall_init_tee(uint8_t* pubkey_out) {
    if (g_initialized) {
        memcpy(pubkey_out,      g_pub_key.gx, 32);
        memcpy(pubkey_out + 32, g_pub_key.gy, 32);
        return SGX_SUCCESS;
    }

    sgx_status_t ret = sgx_ecc256_open_context(&g_ecc_handle);
    if (ret != SGX_SUCCESS) return ret;

    ret = sgx_ecc256_create_key_pair(&g_priv_key, &g_pub_key, g_ecc_handle);
    if (ret != SGX_SUCCESS) return ret;

    g_seen_set   = new std::unordered_set<std::string>();
    g_bof_seen   = new std::unordered_set<std::string>();
    g_initialized = true;

    memcpy(pubkey_out,      g_pub_key.gx, 32);
    memcpy(pubkey_out + 32, g_pub_key.gy, 32);
    return SGX_SUCCESS;
}

sgx_status_t ecall_timestamp_txn(
        const uint8_t* hash,
        int64_t*       timestamp_out,
        uint8_t*       sig_out)
{
    if (!g_initialized) return SGX_ERROR_INVALID_STATE;

    /* Deduplication: the TEE attests each transaction at most once. */
    std::string key = to_hex(hash, 32);
    if (g_seen_set->count(key)) {
        return SGX_ERROR_INVALID_PARAMETER;  /* already attested */
    }

    /* Get time from host via OCALL; enforce monotonicity inside the enclave. */
    int64_t t = 0;
    ocall_get_time(&t);
    if (t <= g_tee_clock) t = g_tee_clock + 1;
    g_tee_clock    = t;
    *timestamp_out = t;

    g_seen_set->insert(key);

    /* Build signed message: hash[32] || timestamp_le[8] */
    uint8_t msg[40];
    memcpy(msg, hash, 32);
    int64_t ts = t;
    for (int i = 0; i < 8; i++) msg[32 + i] = (uint8_t)(ts >> (i * 8));

    /* Compute SHA-256(msg) explicitly so the host can replicate it. */
    sgx_sha256_hash_t digest;
    sgx_status_t ret = sgx_sha256_msg(msg, sizeof(msg), &digest);
    if (ret != SGX_SUCCESS) return ret;

    /* Sign the digest with the enclave's ECDSA-P256 key. */
    sgx_ec256_signature_t sig;
    ret = sgx_ecdsa_sign(
            reinterpret_cast<const uint8_t*>(&digest), sizeof(digest),
            &g_priv_key, &sig, g_ecc_handle);
    if (ret != SGX_SUCCESS) return ret;

    /* Output r || s: each is stored as uint32_t[8] in SGX (little-endian).
     * memcpy copies the raw bytes directly; the host must account for endianness
     * when feeding to OpenSSL (see tee_host.cpp). */
    memcpy(sig_out,      sig.x, 32);
    memcpy(sig_out + 32, sig.y, 32);
    return SGX_SUCCESS;
}

/* Algorithm 4 (BOF): assign a monotonically increasing sequence number.
 * Uses a separate seen-set so OL and BOF attestations are independent.
 * The signed message has the same layout as ecall_timestamp_txn:
 *   msg = hash[32] || seq_le[8]
 * so the host can verify with the same TeeHost::Verify() logic. */
sgx_status_t ecall_assign_sequence_number(
        const uint8_t* hash,
        int64_t*       seq_out,
        uint8_t*       sig_out)
{
    if (!g_initialized) return SGX_ERROR_INVALID_STATE;

    std::string key = to_hex(hash, 32);
    if (g_bof_seen->count(key)) {
        return SGX_ERROR_INVALID_PARAMETER;  /* already attested for BOF */
    }

    int64_t seq = g_seq_counter++;
    *seq_out = seq;
    g_bof_seen->insert(key);

    uint8_t msg[40];
    memcpy(msg, hash, 32);
    for (int i = 0; i < 8; i++) msg[32 + i] = (uint8_t)(seq >> (i * 8));

    /* Pre-hash so host Verify() (which double-hashes) works identically to
     * the timestamp path. */
    sgx_sha256_hash_t digest;
    sgx_status_t ret = sgx_sha256_msg(msg, sizeof(msg), &digest);
    if (ret != SGX_SUCCESS) return ret;

    sgx_ec256_signature_t sig;
    ret = sgx_ecdsa_sign(
            reinterpret_cast<const uint8_t*>(&digest), sizeof(digest),
            &g_priv_key, &sig, g_ecc_handle);
    if (ret != SGX_SUCCESS) return ret;

    memcpy(sig_out,      sig.x, 32);
    memcpy(sig_out + 32, sig.y, 32);
    return SGX_SUCCESS;
}

/* Sign arbitrary bytes (used for TEE-attested last-seen vector L⃗).
 * sgx_ecdsa_sign hashes the input internally (SHA-256), so the host
 * verifies with SHA-256(data) using ECDSA_do_verify. */
sgx_status_t ecall_sign_bytes(
        const uint8_t* data,
        uint32_t       data_len,
        uint8_t*       sig_out)
{
    if (!g_initialized) return SGX_ERROR_INVALID_STATE;
    if (data_len == 0 || data_len > 1024) return SGX_ERROR_INVALID_PARAMETER;

    sgx_ec256_signature_t sig;
    sgx_status_t ret = sgx_ecdsa_sign(
            data, data_len,
            &g_priv_key, &sig, g_ecc_handle);
    if (ret != SGX_SUCCESS) return ret;

    memcpy(sig_out,      sig.x, 32);
    memcpy(sig_out + 32, sig.y, 32);
    return SGX_SUCCESS;
}
